# This is a basic workflow to help you get started with Actions

name: Build and test with GHC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - .github/workflows/build-test.yml
      - rzk/**
      - stack.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Stack
        uses: freckle/stack-action@v4
        with:
          cache-prefix: ${{ runner.os }}-stack-
          pedantic: false

      - name: 🔨 Install BNFC, alex and happy (with Stack)
        run: |
          stack install alex happy BNFC
      - name: 🔨 Generate Syntax files using BNFC
        run: |
          cd rzk/ && (make && make clean; cd ../)

      - name: 🔨 Build dependencies (with Stack)
        run: |
          stack build --only-dependencies

      - name: 🔨 Build and test (with Stack)
        run: |
          stack test
